#!/bin/bash -l
#SBATCH -p quadflat -w cc05
####SBATCH -p quadflat
####SBATCH -p quadcache
#SBATCH --nodes=1
#SBATCH --time=04:00:00
#SBATCH -J quadFlat_job
#SBATCH --output=particle_skeleton.out

## export TOPDIR=/global/u1/t/tnphung/APPSDIR/M3DC1_3D
## echo 'TOPDIR: ' $TOPDIR

## echo 'CURRDIR: ' $CURRDIR
## export SLURM_SUBMIT_DIR=$CURRDIR

export NUMRANKS=4
echo 'Run with ' $NUMRANKS  'MPI RANKS'

export BinDIR=$SLURM_SUBMIT_DIR
echo 'BinDIR: ' $BinDIR

# cd $SLURM_SUBMIT_DIR

module use /usr/common/software/carl_modulefiles
module load intel
module load impi
module load memkind
module load vtune/2016.up3

# time mpirun -np $NUMRANKS numactl -p 1 $BinDIR/m3dc1_pic_skeleton

export VTDir=$SLURM_SUBMIT_DIR
echo "VTDir $VTDir"

export SrcDIR1=$SLURM_SUBMIT_DIR

###export vtuneresultdir=$VTDir/MemoryAccess
export vtuneresultdir=$VTDir/AdvancedHotSpots
### export vtuneresultdir=$VTDir/GeneralExploration
###export vtuneresultdir=$VTDir/HPC

echo "vtuneresultdir $vtuneresultdir"

###export vtunecollection=memory-access
export vtunecollection=advanced-hotspots
### export vtunecollection=general-exploration
###export vtunecollection=hpc-performance

echo "VTune Collection Metric: $vtunecollection"

#mpirun -np 1 amplxe-cl -collect $vtunecollection -data-limit=1024 -quiet -no-auto-finalize \
#       -knob enable-stack-collection=false -knob collect-memory-bandwidth=true \
#       -knob dram-bandwidth-limits=true -knob enable-user-tasks=false -knob analyze-openmp=false \
#       -search-dir=$BinDIR -source-search-dir=$SrcDIR1 \
#       -r $vtuneresultdir -- numactl -p 1 $BinDIR/m3dc1_pic_skeleton : -np 3 numactl -p 1 $BinDIR/m3dc1_pic_skeleton

mpirun -np 1 amplxe-cl -collect $vtunecollection -data-limit=1024 -quiet -no-auto-finalize \
       -search-dir=$BinDIR -source-search-dir=$SrcDIR1 \
       -r $vtuneresultdir -- numactl -p 1 $BinDIR/m3dc1_pic_skeleton : -np 3 numactl -p 1 $BinDIR/m3dc1_pic_skeleton

